// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025 realvirtual GmbH <https://realvirtual.io>

import { defineConfig, devices } from 'playwright/test';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// This config is loaded as an ES module, so `__dirname` does not exist here.
const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Specs that cannot run without the private sibling repo (EP-GOV-004 M3).
 *
 * The unit suites have had this since plan-237 via
 * `tests/private-dependent-tests.json`; the e2e suite never did, so a public
 * checkout could not run it green — four specs reach for
 * `/src/plugins/asset-editor/…`, which exists only in the private sibling, and
 * accounted for 11 of the suite's 24 failures.
 *
 * The list is GENERATED by `scripts/gen-private-test-excludes.mjs`; do not edit
 * it by hand. It is applied ONLY when the private sibling is actually absent,
 * so a full checkout still runs every spec.
 */
const PRIVATE_ROOT = [
  resolve(HERE, '../realvirtual-WebViewer-Private~/src'),
  resolve(HERE, '../realvirtual-web-pro/src'),
].find(existsSync);

function privateDependentSpecs(): RegExp[] {
  if (PRIVATE_ROOT) return [];
  const list = resolve(HERE, 'e2e/private-dependent-specs.json');
  if (!existsSync(list)) return [];
  return (JSON.parse(readFileSync(list, 'utf-8')) as string[])
    .map((name) => new RegExp(`${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`));
}

const PRIVATE_SPECS = privateDependentSpecs();

export default defineConfig({
  testDir: './e2e',
  timeout: 60_000,
  retries: 0,
  /**
   * `channel: 'chromium'` (set per project below) selects Chrome for Testing —
   * the FULL browser in new-headless mode — instead of Playwright's default
   * `chromium-headless-shell`, which has no GPU stack and therefore cannot
   * create a WebGL context at all on macOS. Without it 24 of the 29 specs here
   * simply timed out waiting for `locator('canvas')`, i.e. every assertion after
   * that line had never run. `smoke.spec.ts` went from 4 failed / 1 passed to
   * 5 passed with this one option.
   *
   * Four specs additionally force SOFTWARE rendering with their own
   * `test.use({ launchOptions: { args: ['--use-angle=swiftshader', …] } })`.
   * That is a deliberate determinism choice for the two that make pixel/render
   * assertions, NOT the workaround this option replaces — do not copy those
   * args into a new spec just to make a canvas appear.
   */
  use: {
    baseURL: 'http://localhost:5177',
    headless: true,
    viewport: { width: 1280, height: 720 },
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], channel: 'chromium' },
      testIgnore: [/embed-smoke\.spec\.ts/, ...PRIVATE_SPECS],
    },
    {
      name: 'embed-chromium',
      testMatch: /embed-smoke\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chromium',
        baseURL: 'http://localhost:4178',
      },
    },
  ],
  webServer: [
    {
      command: 'npm run dev -- --port 5177',
      port: 5177,
      reuseExistingServer: true,
      timeout: 30_000,
    },
    {
      command: 'npm run preview:embed',
      port: 4178,
      reuseExistingServer: true,
      timeout: 30_000,
    },
  ],
});
