// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025 realvirtual GmbH <https://realvirtual.io>

/**
 * The incremental hardcoded-text gate (EP-I18N-001 Milestone 1, `GOV-CONSTITUTION` UI-1).
 *
 * `tests/i18n-inventory-baseline.json` is the frozen count of user-visible text
 * still hardcoded in the UI. This test recomputes the scan and fails on ANY
 * difference, in either direction:
 *
 *   - count went UP   → new hardcoded text landed. That is the debt UI-1 forbids
 *                       growing. Route the string through the i18n entry point,
 *                       or register a false positive with a reason in
 *                       scripts/i18n-inventory-exceptions.json.
 *   - count went DOWN → a migration landed and the baseline owes an update:
 *                       `node scripts/i18n-inventory.mjs --write`.
 *
 * Refreshing the baseline is one command precisely so that nobody is tempted to
 * weaken the gate instead. What must never happen is loosening the classifier to
 * make a number go away — the classification rules are the contract here, and
 * the fixture cases below are what keeps them honest in both directions.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
// eslint-disable-next-line import/extensions
import {
  GATED_CATEGORIES,
  SCHEMA_VERSION,
  computeInventory,
  loadExceptions,
  scanSource,
  type I18nFinding,
} from '../scripts/i18n-inventory.mjs';

const ROOT = resolve(__dirname, '..');
const FIXTURES = resolve(ROOT, 'tests/fixtures/i18n-inventory');

/** Category → count, for a set of findings. */
function tally(findings: I18nFinding[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const finding of findings) counts[finding.category] = (counts[finding.category] ?? 0) + 1;
  return counts;
}

/** Scan a fixture under a virtual repo path, so .tsx vs .ts parsing is exercised too. */
function scanFixture(name: string, virtualPath: string): I18nFinding[] {
  return scanSource(virtualPath, readFileSync(resolve(FIXTURES, name), 'utf8'));
}

describe('i18n inventory — incremental hardcoded-text gate', () => {
  const { baseline } = computeInventory(ROOT);
  const committed = JSON.parse(readFileSync(resolve(ROOT, 'tests/i18n-inventory-baseline.json'), 'utf8'));

  it('the committed baseline matches the current scan', () => {
    // Compare totals first: the diff of two 231-entry file maps is unreadable,
    // and the per-category delta is what tells you which surface grew.
    expect(baseline.totals).toEqual(committed.totals);
    expect(baseline.files).toEqual(committed.files);
    expect(baseline.total).toBe(committed.total);
  });

  it('the baseline was generated by the current classifier', () => {
    expect(committed.schemaVersion).toBe(SCHEMA_VERSION);
  });

  it('is non-vacuous — the scan still finds the debt it is meant to track', () => {
    // A gate whose scan silently returns nothing is a green tick over an unchecked
    // repository. These are floors, not targets: they may only be lowered by a
    // migration that also refreshes the baseline.
    expect(baseline.total).toBeGreaterThan(500);
    expect(baseline.totals['react-copy']).toBeGreaterThan(100);
    expect(baseline.fileCount).toBeGreaterThan(50);
  });

  it('covers every gated category in the baseline shape', () => {
    expect(Object.keys(committed.totals).sort()).toEqual([...GATED_CATEGORIES].sort());
  });
});

describe('i18n inventory — classification rules', () => {
  it('classifies the React surfaces', () => {
    const counts = tally(scanFixture('react-copy.tsx.txt', 'src/core/hmi/Fixture.tsx'));
    // JSX text ×2 ("Model signals", "Close"), <Tooltip title> ×1, label/placeholder/helperText ×3
    expect(counts['react-copy']).toBe(6);
    // title on a lowercase host element is an accessible name, not visible copy; plus aria-label
    expect(counts['a11y-name']).toBe(2);
    // interpolated prose in an attribute and as a child
    expect(counts['dynamic-text']).toBe(2);
  });

  it('classifies the non-React surfaces', () => {
    const findings = scanFixture('non-react.ts.txt', 'src/plugins/fixture-plugin.ts');
    const counts = tally(findings);
    expect(counts['plugin-registry']).toBe(3);      // label, tooltip, description — not id/icon
    expect(counts['canvas-texture']).toBe(2);       // literal + both branches of a ternary
    expect(counts['dom-text']).toBe(2);             // literal and interpolated textContent
    expect(counts['error-message']).toBe(1);
    // Prose handed to a rendering state setter, but not the `setBusyFlag('running')`
    // beside it — the suffix convention is the whole signal, and it has to stay narrow.
    expect(counts['ui-state-text']).toBe(1);
    expect(counts['intl-format']).toBe(3);
    // ADR-0001 §6: the actionable number is how many take no explicit locale.
    expect(findings.filter((f) => f.category === 'intl-format' && f.localeExplicit === false)).toHaveLength(1);
  });

  it('treats src/main.ts DOM writes as pre-boot, not ordinary DOM text', () => {
    const source = readFileSync(resolve(FIXTURES, 'non-react.ts.txt'), 'utf8');
    expect(tally(scanSource('src/main.ts', source))['pre-boot']).toBe(2);
    expect(tally(scanSource('src/main.ts', source))['dom-text']).toBeUndefined();
  });

  it('reports nothing for the known false-positive shapes', () => {
    // Styling props, identifiers, kebab ids, enum values, URLs and console output.
    // This is the case that decides whether the gate is usable day to day.
    expect(scanFixture('false-positives.tsx.txt', 'src/core/hmi/Fixture.tsx')).toEqual([]);
  });
});

describe('i18n inventory — exception registry', () => {
  const exceptions = loadExceptions(ROOT);

  it('every exception carries a file, a match and a reason', () => {
    for (const exception of exceptions) {
      expect(exception.file, JSON.stringify(exception)).toBeTruthy();
      expect(exception.match, JSON.stringify(exception)).toBeTruthy();
      // An exception without a stated reason is an unreviewable silent allowance.
      expect(String(exception.reason ?? '').length, JSON.stringify(exception)).toBeGreaterThan(20);
    }
  });

  it('has no exception that matches nothing', () => {
    // A stale exception keeps suppressing whatever moves into its place later.
    const { unusedExceptions } = computeInventory(ROOT);
    expect(unusedExceptions).toEqual([]);
    // Explicit timeout for the same reason as the verbatim gate: a full-tree
    // scan gets slower every batch, and a timeout would be reported as a
    // stale-exception failure that no amount of reading the registry explains.
  }, 60_000);
});
